### ISSUE TITLE
Clarification 

### ISSUE THREAD

**Issue by Konstantin8105** [cpmech/gofem#8]
Hello!
I am a structural engineer.
Could you clarify - have you next finite elements:
- truss FE
- beam FE 
- 2d triangle in 3D system coordination 

Also, can that package calculate a natural frequency, linear and nonlinear buckling 

Thank you for attention

**Comment by cpmech** [comment]
Yes, we have truss and beam (Euler-Bernoulli); but the other features are not implemented yet. Also, please note that Gofem is under a major change.
